### ISSUE TITLE
[Suggestion] Config Rewrite

### ISSUE THREAD

**Issue by BroCrows** [MCPEAbdu77/LevelLimiter#1]
Im just going to say this quickly...
The config sucks!
Instead of making it
```
command1:
  - world1
  - world2
```
 It would be easier to reverse the process, in my opinion.
```
world1:
  - command1
  - command2
```

**Comment by physiciancoder** [comment]
Oh right, this is stupid mistake from my side.

**Comment by physiciancoder** [comment]
make a PR if you're a man
