### ISSUE TITLE
cant use /job at world "Mina"

### ISSUE THREAD

**Issue by UnEnanoMas** [MCPEAbdu77/LevelLimiter#2]
job:
  - "Antiqua"
  - "Anubis"
  - "Artico"
  - "Citas"
  - "Futbol"
  - "Informacion"
  - "Laberinto"
  - "Minijuegos"
  - "Parkour"

**Comment by physiciancoder** [comment]
Add Mina to the list, when you add a command then that command is blacklisted in all the worlds except the ones you added in config

**Comment by UnEnanoMas** [comment]
tpa:
  - "Antiqua"
  - "Anubis"
  - "Artico"
  - "Laberinto"
  - "Parkour"
  
  It doesn't make any sense, because it doesn't let me use / tpa in "Parkour" when the command is set to Parkour

**Comment by physiciancoder** [comment]
Only parkour? Does it work on the other worlds?
The world names are case sensitive btw

**Comment by UnEnanoMas** [comment]
In others it does not work, it is very rare

**Comment by physiciancoder** [comment]
Updated the code a bit and it should fix your issues, will take some time to get approved on poggit but you can download it directly from here.
