### ISSUE TITLE
[FR] Forbid commands completely

### ISSUE THREAD

**Issue by UnEnanoMas** [MCPEAbdu77/LevelLimiter#3]
I currently have the / home command banned from the Parkour world

If you use /home house (being in the world of Parkour) it will take you to house (letting you use the command)

I would also like it to be possible to change the prefix of the plugin xd

**Comment by physiciancoder** [comment]
Thanks for reporting bugs, I'll look into your suggestion.

**Comment by UnEnanoMas** [comment]
It also happens with all the commands that are banned, if you use a space at the end of /fly it lets you activate it even if it is banned from that world

**Comment by UnEnanoMas** [comment]
Dont work at /fly

But it work at /fly "space"

**Comment by ErikPDev** [comment]
Made a PR that fixes this bug #4

**Comment by physiciancoder** [comment]
v1.2.0 has the fixed version and will be on poggit depending on how fast they review the plugin.
